#release configuration
#Fri Nov 08 18:30:40 CET 2024
completedPhase=end-release
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.org.springframework.samples\:spring-petclinic=6.0.1-SNAPSHOT
project.rel.org.springframework.samples\:spring-petclinic=6.0.0
project.scm.org.springframework.samples\:spring-petclinic.developerConnection=scm\:git\:ssh\://git@github.com/adrwalGD/spring-petclinic.git
project.scm.org.springframework.samples\:spring-petclinic.tag=HEAD
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=spring-petclinic-6.0.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:ssh\://git@github.com/adrwalGD/spring-petclinic.git
